apiVersion: v1
kind: Service
metadata:
  name: think-cola-service
  labels:
    app: think-cola
spec:
  selector:
    app: think-cola
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
