apiVersion: v1
kind: Service
metadata:
  name: think-query-service
  labels:
    app: think-query
spec:
  selector:
    app: think-query
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
