apiVersion: apps/v1
kind: Deployment
metadata:
  name: think-query
  labels:
    app: think-query
spec:
  replicas: 1 # 根据需要调整副本数
  selector:
    matchLabels:
      app: think-query
  template:
    metadata:
      labels:
        app: think-query
    spec:
      containers:
        - name: think-query-container
          image: leogao2020/demo:think-query-demo-1.0 # 替换为实际的镜像地址
          ports:
            - containerPort: 8081 # 或者是您的应用监听的端口
          env:
            - name: APP_ENV
              value: "dev" # 环境变量示例